name: "Update Artifacts"
on:
  workflow_dispatch:
  schedule:
  - cron: "0 12 * * *"

jobs:
  update_artifacts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Install dependencies
      run: |
        sudo apt install wget -y
        sudo apt install jq -y
        sudo apt install curl -y
        sudo apt install unzip -y
        sudo apt install tar -y
    - name: Manage folder
      run: |
        mkdir -p artifact
        rm -rf artifact/*
    - name: Download artifacts
      run: |
        cd artifact/
        wget $(curl -s 'https://changelogs-live.fivem.net/api/changelog/versions/linux/server' | jq -r '.latest_download')
        wget $(curl -s 'https://changelogs-live.fivem.net/api/changelog/versions/win32/server' | jq -r '.latest_download')
        unzip server.zip -d windows/
        mkdir linux/
        tar -xf fx.tar.xz -C linux/
        rm -rf server.zip fx.tar.xz
        find . -name "*.git*" -type f -delete
    - name: Commit changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        message: "refactor: updated to \"latest\" artifact"
        branch: "master"
        author_name: "Enz0Z"
        author_email: "enz0z@users.noreply.github.com"
